penny = int(input("How many pennies do you have? "))
quarter = int(penny/25)
dime = int((penny%25)/10)
nickel = int(((penny%25)%10)/5)
penny = int((((penny%25)%10)%5))
print("Quarters:", quarter)
print("Dimes:", dime)
print("Nickels:", nickel)
print("Pennies:", penny)